/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ma.uir.projetintegre;

import java.util.Date;

/**
 *
 * @author tajem
 */
public class fenetreMenuClient extends javax.swing.JFrame {

    /**
     * Creates new form fenetreMenuClient
     */
    public fenetreMenuClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenu = new javax.swing.JPanel();
        lbMenuLogo = new javax.swing.JLabel();
        btnCatalogue = new javax.swing.JButton();
        btnCommander = new javax.swing.JButton();
        btnHistCmds = new javax.swing.JButton();
        btnModifierCmpt = new javax.swing.JButton();
        btnSignOff = new javax.swing.JButton();
        jpSep = new javax.swing.JPanel();
        jtpBoard = new javax.swing.JTabbedPane();
        jpWelcome = new javax.swing.JPanel();
        lbWelcome = new javax.swing.JLabel();
        lbDate = new javax.swing.JLabel();
        jpCatalogue = new javax.swing.JPanel();
        btnRetour1 = new javax.swing.JButton();
        jpCommander = new javax.swing.JPanel();
        btnRetour2 = new javax.swing.JButton();
        jpHistCmds = new javax.swing.JPanel();
        btnRetour3 = new javax.swing.JButton();
        jpModifierCmpt = new javax.swing.JPanel();
        btnRetour4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpMenu.setBackground(new java.awt.Color(255, 255, 255));
        jpMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbMenuLogo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbMenuLogo.setForeground(new java.awt.Color(51, 51, 51));
        lbMenuLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\tajem\\Documents\\NetBeansProjects\\projetIntegre\\src\\main\\java\\ma\\uir\\projetintegre\\icons8_Menu_50px.png")); // NOI18N
        lbMenuLogo.setText("Menu");
        jpMenu.add(lbMenuLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 130, 50));

        btnCatalogue.setText("Catalogue");
        btnCatalogue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogueActionPerformed(evt);
            }
        });
        jpMenu.add(btnCatalogue, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 170, -1));

        btnCommander.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnCommander.setText("Effectuer une commande");
        btnCommander.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommanderActionPerformed(evt);
            }
        });
        jpMenu.add(btnCommander, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 170, -1));

        btnHistCmds.setText("Mes commandes");
        btnHistCmds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistCmdsActionPerformed(evt);
            }
        });
        jpMenu.add(btnHistCmds, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 170, -1));

        btnModifierCmpt.setText("Modifier le compte");
        btnModifierCmpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierCmptActionPerformed(evt);
            }
        });
        jpMenu.add(btnModifierCmpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 170, -1));

        btnSignOff.setText("Se déconnecter");
        btnSignOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOffActionPerformed(evt);
            }
        });
        jpMenu.add(btnSignOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));

        getContentPane().add(jpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 600));

        jpSep.setBackground(new java.awt.Color(255, 153, 102));

        javax.swing.GroupLayout jpSepLayout = new javax.swing.GroupLayout(jpSep);
        jpSep.setLayout(jpSepLayout);
        jpSepLayout.setHorizontalGroup(
            jpSepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jpSepLayout.setVerticalGroup(
            jpSepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jpSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 10, 600));

        jtpBoard.setBackground(new java.awt.Color(255, 255, 255));

        lbWelcome.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbWelcome.setText("Message d'accueil");

        lbDate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbDate.setText("Date");

        javax.swing.GroupLayout jpWelcomeLayout = new javax.swing.GroupLayout(jpWelcome);
        jpWelcome.setLayout(jpWelcomeLayout);
        jpWelcomeLayout.setHorizontalGroup(
            jpWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpWelcomeLayout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(lbWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
            .addGroup(jpWelcomeLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpWelcomeLayout.setVerticalGroup(
            jpWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpWelcomeLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(lbWelcome)
                .addGap(30, 30, 30)
                .addComponent(lbDate)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        jtpBoard.addTab("tab1", jpWelcome);

        btnRetour1.setText("Retour");
        btnRetour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetour1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCatalogueLayout = new javax.swing.GroupLayout(jpCatalogue);
        jpCatalogue.setLayout(jpCatalogueLayout);
        jpCatalogueLayout.setHorizontalGroup(
            jpCatalogueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCatalogueLayout.createSequentialGroup()
                .addContainerGap(604, Short.MAX_VALUE)
                .addComponent(btnRetour1)
                .addGap(26, 26, 26))
        );
        jpCatalogueLayout.setVerticalGroup(
            jpCatalogueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCatalogueLayout.createSequentialGroup()
                .addContainerGap(537, Short.MAX_VALUE)
                .addComponent(btnRetour1)
                .addGap(25, 25, 25))
        );

        jtpBoard.addTab("tab2", jpCatalogue);

        btnRetour2.setText("Retour");
        btnRetour2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetour2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCommanderLayout = new javax.swing.GroupLayout(jpCommander);
        jpCommander.setLayout(jpCommanderLayout);
        jpCommanderLayout.setHorizontalGroup(
            jpCommanderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCommanderLayout.createSequentialGroup()
                .addContainerGap(604, Short.MAX_VALUE)
                .addComponent(btnRetour2)
                .addGap(26, 26, 26))
        );
        jpCommanderLayout.setVerticalGroup(
            jpCommanderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCommanderLayout.createSequentialGroup()
                .addContainerGap(537, Short.MAX_VALUE)
                .addComponent(btnRetour2)
                .addGap(25, 25, 25))
        );

        jtpBoard.addTab("tab3", jpCommander);

        btnRetour3.setText("Retour");
        btnRetour3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetour3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpHistCmdsLayout = new javax.swing.GroupLayout(jpHistCmds);
        jpHistCmds.setLayout(jpHistCmdsLayout);
        jpHistCmdsLayout.setHorizontalGroup(
            jpHistCmdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpHistCmdsLayout.createSequentialGroup()
                .addContainerGap(604, Short.MAX_VALUE)
                .addComponent(btnRetour3)
                .addGap(26, 26, 26))
        );
        jpHistCmdsLayout.setVerticalGroup(
            jpHistCmdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpHistCmdsLayout.createSequentialGroup()
                .addContainerGap(537, Short.MAX_VALUE)
                .addComponent(btnRetour3)
                .addGap(25, 25, 25))
        );

        jtpBoard.addTab("tab4", jpHistCmds);

        btnRetour4.setText("Retour");
        btnRetour4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetour4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpModifierCmptLayout = new javax.swing.GroupLayout(jpModifierCmpt);
        jpModifierCmpt.setLayout(jpModifierCmptLayout);
        jpModifierCmptLayout.setHorizontalGroup(
            jpModifierCmptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpModifierCmptLayout.createSequentialGroup()
                .addContainerGap(604, Short.MAX_VALUE)
                .addComponent(btnRetour4)
                .addGap(26, 26, 26))
        );
        jpModifierCmptLayout.setVerticalGroup(
            jpModifierCmptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpModifierCmptLayout.createSequentialGroup()
                .addContainerGap(537, Short.MAX_VALUE)
                .addComponent(btnRetour4)
                .addGap(25, 25, 25))
        );

        jtpBoard.addTab("tab5", jpModifierCmpt);

        getContentPane().add(jtpBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 700, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistCmdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistCmdsActionPerformed
        jtpBoard.setSelectedIndex(3);
    }//GEN-LAST:event_btnHistCmdsActionPerformed

    private void btnRetour4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetour4ActionPerformed
        jtpBoard.setSelectedIndex(0);
    }//GEN-LAST:event_btnRetour4ActionPerformed

    private void btnRetour3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetour3ActionPerformed
        jtpBoard.setSelectedIndex(0);
    }//GEN-LAST:event_btnRetour3ActionPerformed

    private void btnRetour2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetour2ActionPerformed
        jtpBoard.setSelectedIndex(0);
    }//GEN-LAST:event_btnRetour2ActionPerformed

    private void btnRetour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetour1ActionPerformed
        jtpBoard.setSelectedIndex(0);
    }//GEN-LAST:event_btnRetour1ActionPerformed

    private void btnSignOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOffActionPerformed
        dispose();
        new fenetreLogin().setVisible(true);
    }//GEN-LAST:event_btnSignOffActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lbDate.setText(new Date().toString());
    }//GEN-LAST:event_formWindowOpened

    private void btnCatalogueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogueActionPerformed
        jtpBoard.setSelectedIndex(1);
    }//GEN-LAST:event_btnCatalogueActionPerformed

    private void btnCommanderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommanderActionPerformed
        jtpBoard.setSelectedIndex(2);
    }//GEN-LAST:event_btnCommanderActionPerformed

    private void btnModifierCmptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierCmptActionPerformed
        jtpBoard.setSelectedIndex(4);
    }//GEN-LAST:event_btnModifierCmptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetreMenuClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetreMenuClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetreMenuClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetreMenuClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetreMenuClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCatalogue;
    private javax.swing.JButton btnCommander;
    private javax.swing.JButton btnHistCmds;
    private javax.swing.JButton btnModifierCmpt;
    private javax.swing.JButton btnRetour1;
    private javax.swing.JButton btnRetour2;
    private javax.swing.JButton btnRetour3;
    private javax.swing.JButton btnRetour4;
    private javax.swing.JButton btnSignOff;
    private javax.swing.JPanel jpCatalogue;
    private javax.swing.JPanel jpCommander;
    private javax.swing.JPanel jpHistCmds;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpModifierCmpt;
    private javax.swing.JPanel jpSep;
    private javax.swing.JPanel jpWelcome;
    private javax.swing.JTabbedPane jtpBoard;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbMenuLogo;
    private javax.swing.JLabel lbWelcome;
    // End of variables declaration//GEN-END:variables
}
