/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ma.uir.projetintegre;

import java.util.Date;

/**
 *
 * @author tajem
 */
public class fenetreMenu extends javax.swing.JFrame {

    /**
     * Creates new form fenetreMenu
     */
    public fenetreMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenu = new javax.swing.JPanel();
        lbMenuLogo = new javax.swing.JLabel();
        btnGererFrs = new javax.swing.JButton();
        btnGererPrds = new javax.swing.JButton();
        btnHistCmds = new javax.swing.JButton();
        btnGererCmpts = new javax.swing.JButton();
        btnSignOff = new javax.swing.JButton();
        jpSep = new javax.swing.JPanel();
        jtpBoard = new javax.swing.JTabbedPane();
        jpWelcome = new javax.swing.JPanel();
        lbWelcome = new javax.swing.JLabel();
        lbDate = new javax.swing.JLabel();
        jpMenuFrs = new javax.swing.JPanel();
        btnListerFrs = new javax.swing.JButton();
        btnAjouterFrs = new javax.swing.JButton();
        btnSupFrs = new javax.swing.JButton();
        btnModifierFrs = new javax.swing.JButton();
        jpMenuPrds = new javax.swing.JPanel();
        btnSupProd = new javax.swing.JButton();
        btnModifierPrd = new javax.swing.JButton();
        btnAjouterPrd = new javax.swing.JButton();
        btnListerPrds = new javax.swing.JButton();
        jpHistCmds = new javax.swing.JPanel();
        btnRetour3 = new javax.swing.JButton();
        jpMenuCmpts = new javax.swing.JPanel();
        btnListerCmpts = new javax.swing.JButton();
        btnAjouterCmpt = new javax.swing.JButton();
        btnSupCmpt = new javax.swing.JButton();
        jpListerFrs = new javax.swing.JPanel();
        btnRetour5 = new javax.swing.JButton();
        jpAjouterFrs = new javax.swing.JPanel();
        btnRetour6 = new javax.swing.JButton();
        jpListerPrds = new javax.swing.JPanel();
        btnRetour7 = new javax.swing.JButton();
        jpAjouterPrd = new javax.swing.JPanel();
        btnRetour8 = new javax.swing.JButton();
        jpVide = new javax.swing.JPanel();
        btnRetour9 = new javax.swing.JButton();
        jpListerCmpts = new javax.swing.JPanel();
        btnRetour10 = new javax.swing.JButton();
        jpAjouterCmpt = new javax.swing.JPanel();
        btnRetour11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 102));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpMenu.setBackground(new java.awt.Color(255, 255, 255));
        jpMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbMenuLogo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbMenuLogo.setForeground(new java.awt.Color(51, 51, 51));
        lbMenuLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\tajem\\Documents\\NetBeansProjects\\projetIntegre\\src\\main\\java\\ma\\uir\\projetintegre\\icons8_Menu_50px.png")); // NOI18N
        lbMenuLogo.setText("Menu");
        jpMenu.add(lbMenuLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 130, 50));

        btnGererFrs.setText("Gérer les fournisseurs");
        btnGererFrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGererFrsActionPerformed(evt);
            }
        });
        jpMenu.add(btnGererFrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 170, -1));

        btnGererPrds.setText("Gérer les produits");
        btnGererPrds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGererPrdsActionPerformed(evt);
            }
        });
        jpMenu.add(btnGererPrds, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 170, -1));

        btnHistCmds.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnHistCmds.setText("Historique des commandes");
        btnHistCmds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistCmdsActionPerformed(evt);
            }
        });
        jpMenu.add(btnHistCmds, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 170, -1));

        btnGererCmpts.setText("Gérer les comptes");
        btnGererCmpts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGererCmptsActionPerformed(evt);
            }
        });
        jpMenu.add(btnGererCmpts, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 170, -1));

        btnSignOff.setText("Se déconnecter");
        btnSignOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOffActionPerformed(evt);
            }
        });
        jpMenu.add(btnSignOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));

        getContentPane().add(jpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 600));

        jpSep.setBackground(new java.awt.Color(255, 153, 102));

        javax.swing.GroupLayout jpSepLayout = new javax.swing.GroupLayout(jpSep);
        jpSep.setLayout(jpSepLayout);
        jpSepLayout.setHorizontalGroup(
            jpSepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jpSepLayout.setVerticalGroup(
            jpSepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jpSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 10, 600));

        jtpBoard.setBackground(new java.awt.Color(255, 255, 255));

        lbWelcome.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbWelcome.setText("Message d'accueil");

        lbDate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbDate.setText("Date");

        javax.swing.GroupLayout jpWelcomeLayout = new javax.swing.GroupLayout(jpWelcome);
        jpWelcome.setLayout(jpWelcomeLayout);
        jpWelcomeLayout.setHorizontalGroup(
            jpWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpWelcomeLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(jpWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jpWelcomeLayout.setVerticalGroup(
            jpWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpWelcomeLayout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(lbWelcome)
                .addGap(38, 38, 38)
                .addComponent(lbDate)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        jtpBoard.addTab("tab1", jpWelcome);

        btnListerFrs.setText("Lister les fournisseurs");
        btnListerFrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListerFrsActionPerformed(evt);
            }
        });

        btnAjouterFrs.setText("Ajouter un fournisseur");
        btnAjouterFrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterFrsActionPerformed(evt);
            }
        });

        btnSupFrs.setText("Supprimer un fournisseur");
        btnSupFrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupFrsActionPerformed(evt);
            }
        });

        btnModifierFrs.setText("Modifier un fournisseur");
        btnModifierFrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierFrsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuFrsLayout = new javax.swing.GroupLayout(jpMenuFrs);
        jpMenuFrs.setLayout(jpMenuFrsLayout);
        jpMenuFrsLayout.setHorizontalGroup(
            jpMenuFrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuFrsLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(jpMenuFrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnModifierFrs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSupFrs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAjouterFrs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListerFrs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jpMenuFrsLayout.setVerticalGroup(
            jpMenuFrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuFrsLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(btnListerFrs)
                .addGap(18, 18, 18)
                .addComponent(btnAjouterFrs)
                .addGap(18, 18, 18)
                .addComponent(btnModifierFrs)
                .addGap(18, 18, 18)
                .addComponent(btnSupFrs)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        jtpBoard.addTab("tab2", jpMenuFrs);

        btnSupProd.setText("Supprimer un produit");
        btnSupProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupProdActionPerformed(evt);
            }
        });

        btnModifierPrd.setText("Modifier un produit");
        btnModifierPrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierPrdActionPerformed(evt);
            }
        });

        btnAjouterPrd.setText("Ajouter un produit");
        btnAjouterPrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterPrdActionPerformed(evt);
            }
        });

        btnListerPrds.setText("Lister les produits");
        btnListerPrds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListerPrdsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuPrdsLayout = new javax.swing.GroupLayout(jpMenuPrds);
        jpMenuPrds.setLayout(jpMenuPrdsLayout);
        jpMenuPrdsLayout.setHorizontalGroup(
            jpMenuPrdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuPrdsLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(jpMenuPrdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnModifierPrd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSupProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAjouterPrd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListerPrds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(298, Short.MAX_VALUE))
        );
        jpMenuPrdsLayout.setVerticalGroup(
            jpMenuPrdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuPrdsLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(btnListerPrds)
                .addGap(18, 18, 18)
                .addComponent(btnAjouterPrd)
                .addGap(18, 18, 18)
                .addComponent(btnModifierPrd)
                .addGap(18, 18, 18)
                .addComponent(btnSupProd)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        jtpBoard.addTab("tab3", jpMenuPrds);

        btnRetour3.setText("Retour");
        btnRetour3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetour3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpHistCmdsLayout = new javax.swing.GroupLayout(jpHistCmds);
        jpHistCmds.setLayout(jpHistCmdsLayout);
        jpHistCmdsLayout.setHorizontalGroup(
            jpHistCmdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpHistCmdsLayout.createSequentialGroup()
                .addContainerGap(604, Short.MAX_VALUE)
                .addComponent(btnRetour3)
                .addGap(26, 26, 26))
        );
        jpHistCmdsLayout.setVerticalGroup(
            jpHistCmdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpHistCmdsLayout.createSequentialGroup()
                .addContainerGap(537, Short.MAX_VALUE)
                .addComponent(btnRetour3)
                .addGap(25, 25, 25))
        );

        jtpBoard.addTab("tab4", jpHistCmds);

        btnListerCmpts.setText("Lister les comptes");
        btnListerCmpts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListerCmptsActionPerformed(evt);
            }
        });

        btnAjouterCmpt.setText("Ajouter un compte");
        btnAjouterCmpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterCmptActionPerformed(evt);
            }
        });

        btnSupCmpt.setText("Supprimer un compte");
        btnSupCmpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupCmptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuCmptsLayout = new javax.swing.GroupLayout(jpMenuCmpts);
        jpMenuCmpts.setLayout(jpMenuCmptsLayout);
        jpMenuCmptsLayout.setHorizontalGroup(
            jpMenuCmptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuCmptsLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addGroup(jpMenuCmptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSupCmpt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAjouterCmpt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListerCmpts, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        jpMenuCmptsLayout.setVerticalGroup(
            jpMenuCmptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuCmptsLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(btnListerCmpts)
                .addGap(18, 18, 18)
                .addComponent(btnAjouterCmpt)
                .addGap(18, 18, 18)
                .addComponent(btnSupCmpt)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        jtpBoard.addTab("tab5", jpMenuCmpts);

        btnRetour5.setText("Retour");
        btnRetour5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetour5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpListerFrsLayout = new javax.swing.GroupLayout(jpListerFrs);
        jpListerFrs.setLayout(jpListerFrsLayout);
        jpListerFrsLayout.setHorizontalGroup(
            jpListerFrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpListerFrsLayout.createSequentialGroup()
                .addContainerGap(604, Short.MAX_VALUE)
                .addComponent(btnRetour5)
                .addGap(26, 26, 26))
        );
        jpListerFrsLayout.setVerticalGroup(
            jpListerFrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpListerFrsLayout.createSequentialGroup()
                .addContainerGap(537, Short.MAX_VALUE)
                .addComponent(btnRetour5)
                .addGap(25, 25, 25))
        );

        jtpBoard.addTab("tab6", jpListerFrs);

        btnRetour6.setText("Retour");
        btnRetour6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetour6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpAjouterFrsLayout = new javax.swing.GroupLayout(jpAjouterFrs);
        jpAjouterFrs.setLayout(jpAjouterFrsLayout);
        jpAjouterFrsLayout.setHorizontalGroup(
            jpAjouterFrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAjouterFrsLayout.createSequentialGroup()
                .addContainerGap(604, Short.MAX_VALUE)
                .addComponent(btnRetour6)
                .addGap(26, 26, 26))
        );
        jpAjouterFrsLayout.setVerticalGroup(
            jpAjouterFrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAjouterFrsLayout.createSequentialGroup()
                .addContainerGap(537, Short.MAX_VALUE)
                .addComponent(btnRetour6)
                .addGap(25, 25, 25))
        );

        jtpBoard.addTab("tab7", jpAjouterFrs);

        btnRetour7.setText("Retour");
        btnRetour7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetour7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpListerPrdsLayout = new javax.swing.GroupLayout(jpListerPrds);
        jpListerPrds.setLayout(jpListerPrdsLayout);
        jpListerPrdsLayout.setHorizontalGroup(
            jpListerPrdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpListerPrdsLayout.createSequentialGroup()
                .addContainerGap(604, Short.MAX_VALUE)
                .addComponent(btnRetour7)
                .addGap(26, 26, 26))
        );
        jpListerPrdsLayout.setVerticalGroup(
            jpListerPrdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpListerPrdsLayout.createSequentialGroup()
                .addContainerGap(537, Short.MAX_VALUE)
                .addComponent(btnRetour7)
                .addGap(25, 25, 25))
        );

        jtpBoard.addTab("tab8", jpListerPrds);

        btnRetour8.setText("Retour");
        btnRetour8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetour8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpAjouterPrdLayout = new javax.swing.GroupLayout(jpAjouterPrd);
        jpAjouterPrd.setLayout(jpAjouterPrdLayout);
        jpAjouterPrdLayout.setHorizontalGroup(
            jpAjouterPrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAjouterPrdLayout.createSequentialGroup()
                .addContainerGap(604, Short.MAX_VALUE)
                .addComponent(btnRetour8)
                .addGap(26, 26, 26))
        );
        jpAjouterPrdLayout.setVerticalGroup(
            jpAjouterPrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAjouterPrdLayout.createSequentialGroup()
                .addContainerGap(537, Short.MAX_VALUE)
                .addComponent(btnRetour8)
                .addGap(25, 25, 25))
        );

        jtpBoard.addTab("tab9", jpAjouterPrd);

        btnRetour9.setText("Retour");
        btnRetour9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetour9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpVideLayout = new javax.swing.GroupLayout(jpVide);
        jpVide.setLayout(jpVideLayout);
        jpVideLayout.setHorizontalGroup(
            jpVideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpVideLayout.createSequentialGroup()
                .addContainerGap(604, Short.MAX_VALUE)
                .addComponent(btnRetour9)
                .addGap(26, 26, 26))
        );
        jpVideLayout.setVerticalGroup(
            jpVideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpVideLayout.createSequentialGroup()
                .addContainerGap(537, Short.MAX_VALUE)
                .addComponent(btnRetour9)
                .addGap(25, 25, 25))
        );

        jtpBoard.addTab("tab10", jpVide);

        btnRetour10.setText("Retour");
        btnRetour10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetour10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpListerCmptsLayout = new javax.swing.GroupLayout(jpListerCmpts);
        jpListerCmpts.setLayout(jpListerCmptsLayout);
        jpListerCmptsLayout.setHorizontalGroup(
            jpListerCmptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpListerCmptsLayout.createSequentialGroup()
                .addContainerGap(604, Short.MAX_VALUE)
                .addComponent(btnRetour10)
                .addGap(26, 26, 26))
        );
        jpListerCmptsLayout.setVerticalGroup(
            jpListerCmptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpListerCmptsLayout.createSequentialGroup()
                .addContainerGap(537, Short.MAX_VALUE)
                .addComponent(btnRetour10)
                .addGap(25, 25, 25))
        );

        jtpBoard.addTab("tab11", jpListerCmpts);

        btnRetour11.setText("Retour");
        btnRetour11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetour11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpAjouterCmptLayout = new javax.swing.GroupLayout(jpAjouterCmpt);
        jpAjouterCmpt.setLayout(jpAjouterCmptLayout);
        jpAjouterCmptLayout.setHorizontalGroup(
            jpAjouterCmptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAjouterCmptLayout.createSequentialGroup()
                .addContainerGap(604, Short.MAX_VALUE)
                .addComponent(btnRetour11)
                .addGap(26, 26, 26))
        );
        jpAjouterCmptLayout.setVerticalGroup(
            jpAjouterCmptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAjouterCmptLayout.createSequentialGroup()
                .addContainerGap(537, Short.MAX_VALUE)
                .addComponent(btnRetour11)
                .addGap(25, 25, 25))
        );

        jtpBoard.addTab("tab12", jpAjouterCmpt);

        getContentPane().add(jtpBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 700, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterFrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterFrsActionPerformed
        jtpBoard.setSelectedIndex(6);
    }//GEN-LAST:event_btnAjouterFrsActionPerformed

    private void btnListerFrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListerFrsActionPerformed
        jtpBoard.setSelectedIndex(5);
    }//GEN-LAST:event_btnListerFrsActionPerformed

    private void btnSupFrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupFrsActionPerformed
        jtpBoard.setSelectedIndex(5);
    }//GEN-LAST:event_btnSupFrsActionPerformed

    private void btnModifierFrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierFrsActionPerformed
        jtpBoard.setSelectedIndex(5);
    }//GEN-LAST:event_btnModifierFrsActionPerformed

    private void btnSupProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupProdActionPerformed
        jtpBoard.setSelectedIndex(7);
    }//GEN-LAST:event_btnSupProdActionPerformed

    private void btnModifierPrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierPrdActionPerformed
        jtpBoard.setSelectedIndex(7);
    }//GEN-LAST:event_btnModifierPrdActionPerformed

    private void btnAjouterPrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterPrdActionPerformed
        jtpBoard.setSelectedIndex(8);
    }//GEN-LAST:event_btnAjouterPrdActionPerformed

    private void btnListerPrdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListerPrdsActionPerformed
        jtpBoard.setSelectedIndex(7);
    }//GEN-LAST:event_btnListerPrdsActionPerformed

    private void btnListerCmptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListerCmptsActionPerformed
        jtpBoard.setSelectedIndex(10);
    }//GEN-LAST:event_btnListerCmptsActionPerformed

    private void btnAjouterCmptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterCmptActionPerformed
        jtpBoard.setSelectedIndex(11);
    }//GEN-LAST:event_btnAjouterCmptActionPerformed

    private void btnSupCmptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupCmptActionPerformed
        jtpBoard.setSelectedIndex(10);
    }//GEN-LAST:event_btnSupCmptActionPerformed

    private void btnSignOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOffActionPerformed
        dispose();
        new fenetreLogin().setVisible(true);
    }//GEN-LAST:event_btnSignOffActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lbDate.setText(new Date().toString());
    }//GEN-LAST:event_formWindowOpened

    private void btnRetour5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetour5ActionPerformed
        jtpBoard.setSelectedIndex(1);
    }//GEN-LAST:event_btnRetour5ActionPerformed

    private void btnRetour6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetour6ActionPerformed
        jtpBoard.setSelectedIndex(1);
    }//GEN-LAST:event_btnRetour6ActionPerformed

    private void btnRetour7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetour7ActionPerformed
        jtpBoard.setSelectedIndex(2);
    }//GEN-LAST:event_btnRetour7ActionPerformed

    private void btnRetour8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetour8ActionPerformed
        jtpBoard.setSelectedIndex(2);
    }//GEN-LAST:event_btnRetour8ActionPerformed

    private void btnRetour9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetour9ActionPerformed
        jtpBoard.setSelectedIndex(3);
    }//GEN-LAST:event_btnRetour9ActionPerformed

    private void btnRetour10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetour10ActionPerformed
        jtpBoard.setSelectedIndex(4);
    }//GEN-LAST:event_btnRetour10ActionPerformed

    private void btnRetour11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetour11ActionPerformed
        jtpBoard.setSelectedIndex(4);
    }//GEN-LAST:event_btnRetour11ActionPerformed

    private void btnHistCmdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistCmdsActionPerformed
        jtpBoard.setSelectedIndex(3);
    }//GEN-LAST:event_btnHistCmdsActionPerformed

    private void btnRetour3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetour3ActionPerformed
        jtpBoard.setSelectedIndex(0);
    }//GEN-LAST:event_btnRetour3ActionPerformed

    private void btnGererFrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGererFrsActionPerformed
        jtpBoard.setSelectedIndex(1);
    }//GEN-LAST:event_btnGererFrsActionPerformed

    private void btnGererPrdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGererPrdsActionPerformed
        jtpBoard.setSelectedIndex(2);
    }//GEN-LAST:event_btnGererPrdsActionPerformed

    private void btnGererCmptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGererCmptsActionPerformed
        jtpBoard.setSelectedIndex(4);
    }//GEN-LAST:event_btnGererCmptsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetreMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetreMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetreMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetreMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetreMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterCmpt;
    private javax.swing.JButton btnAjouterFrs;
    private javax.swing.JButton btnAjouterPrd;
    private javax.swing.JButton btnGererCmpts;
    private javax.swing.JButton btnGererFrs;
    private javax.swing.JButton btnGererPrds;
    private javax.swing.JButton btnHistCmds;
    private javax.swing.JButton btnListerCmpts;
    private javax.swing.JButton btnListerFrs;
    private javax.swing.JButton btnListerPrds;
    private javax.swing.JButton btnModifierFrs;
    private javax.swing.JButton btnModifierPrd;
    private javax.swing.JButton btnRetour10;
    private javax.swing.JButton btnRetour11;
    private javax.swing.JButton btnRetour3;
    private javax.swing.JButton btnRetour5;
    private javax.swing.JButton btnRetour6;
    private javax.swing.JButton btnRetour7;
    private javax.swing.JButton btnRetour8;
    private javax.swing.JButton btnRetour9;
    private javax.swing.JButton btnSignOff;
    private javax.swing.JButton btnSupCmpt;
    private javax.swing.JButton btnSupFrs;
    private javax.swing.JButton btnSupProd;
    private javax.swing.JPanel jpAjouterCmpt;
    private javax.swing.JPanel jpAjouterFrs;
    private javax.swing.JPanel jpAjouterPrd;
    private javax.swing.JPanel jpHistCmds;
    private javax.swing.JPanel jpListerCmpts;
    private javax.swing.JPanel jpListerFrs;
    private javax.swing.JPanel jpListerPrds;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpMenuCmpts;
    private javax.swing.JPanel jpMenuFrs;
    private javax.swing.JPanel jpMenuPrds;
    private javax.swing.JPanel jpSep;
    private javax.swing.JPanel jpVide;
    private javax.swing.JPanel jpWelcome;
    private javax.swing.JTabbedPane jtpBoard;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbMenuLogo;
    private javax.swing.JLabel lbWelcome;
    // End of variables declaration//GEN-END:variables
}
