/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ma.uir.projetintegre;

import java.awt.Color;
import java.time.LocalDate;
import java.util.Date;

/**
 *
 * @author tajem
 */
public class fenetreLogin extends javax.swing.JFrame {

    /**
     * Creates new form fenetreLogin
     */
    
    public fenetreLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        lbId = new javax.swing.JLabel();
        lbPwd = new javax.swing.JLabel();
        tfDum = new javax.swing.JTextField();
        btnSignIn = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        tfPwd = new javax.swing.JPasswordField();
        showPwd = new javax.swing.JCheckBox();
        tfId = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lbDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\tajem\\Documents\\NetBeansProjects\\projetIntegre\\src\\main\\java\\ma\\uir\\projetintegre\\mouja (200 × 200 px).png")); // NOI18N
        jPanel1.add(lbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, 160));

        lbId.setIcon(new javax.swing.ImageIcon("C:\\Users\\tajem\\Documents\\NetBeansProjects\\projetIntegre\\src\\main\\java\\ma\\uir\\projetintegre\\icons8_user_20px_2.png")); // NOI18N
        jPanel1.add(lbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 20, 50));

        lbPwd.setIcon(new javax.swing.ImageIcon("C:\\Users\\tajem\\Documents\\NetBeansProjects\\projetIntegre\\src\\main\\java\\ma\\uir\\projetintegre\\icons8_password_20px.png")); // NOI18N
        jPanel1.add(lbPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, 30));

        tfDum.setText("jTextField1");
        jPanel1.add(tfDum, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 10, -1));

        btnSignIn.setText("Se connecter");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        btnSignUp.setText("S'enregistrer");
        jPanel1.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, -1, -1));

        tfPwd.setBackground(new java.awt.Color(255, 255, 255));
        tfPwd.setForeground(java.awt.Color.gray);
        tfPwd.setText("$$$$$$");
        tfPwd.setBorder(null);
        tfPwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPwdFocusGained(evt);
            }
        });
        tfPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPwdActionPerformed(evt);
            }
        });
        jPanel1.add(tfPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 130, -1));

        showPwd.setText("Afficher le mot de passe");
        showPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPwdActionPerformed(evt);
            }
        });
        jPanel1.add(showPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        tfId.setBackground(new java.awt.Color(255, 255, 255));
        tfId.setForeground(java.awt.Color.gray);
        tfId.setText("Identifiant");
        tfId.setBorder(null);
        tfId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfIdFocusGained(evt);
            }
        });
        tfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdActionPerformed(evt);
            }
        });
        jPanel1.add(tfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 130, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 120, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 120, 20));

        lbDate.setText("Date");
        jPanel1.add(lbDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignInActionPerformed

    private void tfPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPwdActionPerformed

    private void showPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPwdActionPerformed
        if(showPwd.isSelected())
            tfPwd.setEchoChar((char)0);
        else
            tfPwd.setEchoChar('*');
    }//GEN-LAST:event_showPwdActionPerformed

    private void tfPwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPwdFocusGained
        tfPwd.setForeground(Color.BLACK);
        tfPwd.setText(null);
    }//GEN-LAST:event_tfPwdFocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tfDum.setVisible(false);
        lbDate.setText(new Date().toString());
    }//GEN-LAST:event_formWindowOpened

    private void tfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdActionPerformed

    private void tfIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfIdFocusGained
        tfId.setForeground(Color.BLACK);
        tfId.setText(null);
        
    }//GEN-LAST:event_tfIdFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetreLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetreLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetreLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetreLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new fenetreLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbPwd;
    private javax.swing.JCheckBox showPwd;
    private javax.swing.JTextField tfDum;
    private javax.swing.JTextField tfId;
    private javax.swing.JPasswordField tfPwd;
    // End of variables declaration//GEN-END:variables
}
